---
title: "Stuff 03"
author: "Keith Baggerly"
date: "`r Sys.Date()`"
output: 
  word_document: 
    reference_docx: !expr system.file("extdata", "ref01.docx", package = "moffitt2018")
  html_document: default
---

# Stuff here

stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
stuff stuff stuff stuff stuff stuff stuff  
